dist: xenial
sudo: required

language: node_js
node_js:
  - "8.11.3"
  
cache:
  directories:
  - node_modules


before_install:
  - echo "Start Build for Hexo Blog, kmahyyg.github.io"
#  - ls -al /home/travis/build/iriberri-org/kmahyyg.github.io/node_modules
#  - ls -al /home/travis/build/iriberri-org/kmahyyg.github.io/node_modules/hexo
#  - ls -al /home/travis/build/iriberri-org/kmahyyg.github.io/node_modules/.bin

install:
  - npm install hexo-cli -g --save
#  - npm install hexo-helper-qrcode
#  - npm install hexo-generator-feed
#  - npm install hexo-deployer-git
#  - npm install hexo-prism-plugin
#  - npm install hexo-generator-search
#  - npm install hexo
#  - npm install hexo-generator-sitemap
   - npm install hexo hexo-deployer-git hexo-prism-plugin hexo-helper-qrcode hexo-generator-search hexo-generator-sitemap hexo-generator-feed --save 
  
  
  
script:
  - which hexo
  - hexo g --debug


